import type { Metadata } from "next";
import { Fraunces, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/global/NavBar";
import Footer from "@/components/global/footer";
import ContactSection from "@/components/ui/contactSection";

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-body",
  subsets: ["latin"],
});

const fraunces = Fraunces({
  variable: "--font-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/vercel.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jakartaSans.variable} ${fraunces.variable} antialiased`}>
        <NavbarComponent />
        <main>{children}</main>
        <ContactSection />
        <Footer />
      </body>
    </html>
  );
}
